export const OriginObjects={
    AbortController,
    TypeError,
    Promise,
    Object:{
        freeze:Object.freeze,
    },
    Reflect:{
        has:Reflect.has,
    },
    Proxy,
    String:{
        toString:String.prototype.toString,
        includes:String.prototype.includes,
    },
    console:{
        log:console.log,
        warn:console.warn,
        error:console.error
    },
    open,
    navigator:{
        clipboard:{
            writeText:navigator.clipboard.writeText.bind(navigator.clipboard),
            write:navigator.clipboard.write.bind(navigator.clipboard),
        }
    }
}
OriginObjects.Object.freeze(OriginObjects);