export const OriginObjects={
    AbortController,
    TypeError,
    Object:{
        freeze:Object.freeze,
    },
    Reflect:{
        has:Reflect.has,
    },
    Proxy,
    String:{
        toString:String.prototype.toString,
        includes:String.prototype.includes,
    },
    console:{
        log:console.log,
        warn:console.warn,
        error:console.error
    },
    open
}
OriginObjects.Object.freeze(OriginObjects);